import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { createInterface } from 'node:readline'
import { join, resolve, dirname } from 'node:path'
import { homedir } from 'node:os'
import { fileURLToPath } from 'node:url'

// Repo root resolved from this module's own location: dist/cli/install.js (or
// src/cli/install.ts in dev) — two levels below the root.
const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const OPENCODE_CONFIG_DIR = process.env.OPENCODE_CONFIG_DIR ?? join(homedir(), '.config', 'opencode')
const PLUGINS_DIR = join(OPENCODE_CONFIG_DIR, 'plugins')
const BRIDGE_FILE = join(PLUGINS_DIR, 'opencode-remote-control.js')
const PKG_JSON = join(OPENCODE_CONFIG_DIR, 'package.json')
const GLOBAL_OPENCODE_JSON = join(OPENCODE_CONFIG_DIR, 'opencode.json')
const ENTRY = join(REPO_ROOT, 'dist', 'plugin', 'entry.js')
const ENV_FILE = join(REPO_ROOT, '.env')
const DEFAULT_WEB_PORT = '17081' // opencode 1.17's own server uses 7081

interface InstallOptions {
  yes: boolean
}

async function ask(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  return new Promise<string>((res) => rl.question(question, res))
}

/** Read existing .env (if any) into a key→value map, preserving comments isn't needed for upsert. */
function readEnv(): Map<string, string> {
  const map = new Map<string, string>()
  if (!existsSync(ENV_FILE)) return map
  for (const line of readFileSync(ENV_FILE, 'utf-8').split('\n')) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/)
    if (m) map.set(m[1], m[2])
  }
  return map
}

/** Upsert keys into .env, preserving existing keys/comments not being changed. */
function upsertEnv(updates: Record<string, string>): void {
  const lines = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, 'utf-8').split('\n') : []
  const remaining = { ...updates }
  const out = lines.map((line) => {
    const m = line.match(/^([A-Z0-9_]+)=/)
    if (m && m[1] in remaining) {
      const v = remaining[m[1]]
      delete remaining[m[1]]
      return `${m[1]}=${v}`
    }
    return line
  })
  for (const [k, v] of Object.entries(remaining)) out.push(`${k}=${v}`)
  writeFileSync(ENV_FILE, out.join('\n').replace(/\n*$/, '\n'))
}

/** Create the ~/.config/opencode/plugins/ bridge that re-invokes our built plugin. */
function writeBridge(): void {
  mkdirSync(PLUGINS_DIR, { recursive: true })
  writeFileSync(
    BRIDGE_FILE,
    `// Auto-generated by opencode-remote-control install.
// opencode 1.17 loads local plugins from ~/.config/opencode/plugins/ and only
// invokes functions DEFINED in the loaded module (re-exports are imported but
// never called), so we wrap the built plugin in a locally-defined function.
// The repo's dist stays the source of truth — rebuild dist + restart opencode
// to pick up changes.
import plugin from ${JSON.stringify(ENTRY)}

export const opencodeRemoteControl = async (ctx) => plugin(ctx)
`,
  )
  // Ensure the bare .js bridge is parsed as ESM.
  let pkg: Record<string, unknown> = {}
  if (existsSync(PKG_JSON)) {
    try { pkg = JSON.parse(readFileSync(PKG_JSON, 'utf-8')) } catch { pkg = {} }
  }
  if (pkg.type !== 'module') {
    pkg.type = 'module'
    writeFileSync(PKG_JSON, JSON.stringify(pkg, null, 2) + '\n')
  }
}

/** Remove the legacy directory-path plugin entry from opencode.json (1.16 and earlier). */
function migrateLegacyConfig(): boolean {
  if (!existsSync(GLOBAL_OPENCODE_JSON)) return false
  let config: Record<string, any>
  try { config = JSON.parse(readFileSync(GLOBAL_OPENCODE_JSON, 'utf-8')) } catch { return false }
  const plugins: Array<string | [string, unknown]> = config.plugin ?? []
  const isLegacy = (e: string | [string, unknown]) => {
    const name = Array.isArray(e) ? e[0] : e
    return name === REPO_ROOT || name === 'opencode-remote-control@latest' || /opencode-remote-control$/.test(name)
  }
  const filtered = plugins.filter((e) => !isLegacy(e))
  if (filtered.length === plugins.length) return false
  config.plugin = filtered
  writeFileSync(GLOBAL_OPENCODE_JSON, JSON.stringify(config, null, 2) + '\n')
  return true
}

export async function runInstall(options: InstallOptions): Promise<void> {
  console.log(`\nInstalling opencode-remote-control for opencode 1.17+...\n`)
  console.log(`   Repo:    ${REPO_ROOT}`)
  console.log(`   Bridge:  ${BRIDGE_FILE}`)
  console.log(`   Env:     ${ENV_FILE}`)

  if (!existsSync(ENTRY)) {
    console.error(`\n  dist not built: ${ENTRY} is missing. Run \`npm run build\` first.`)
    process.exit(1)
  }

  const env = readEnv()
  let token = env.get('TELEGRAM_BOT_TOKEN') ?? process.env.TELEGRAM_BOT_TOKEN ?? ''
  let ids = env.get('ALLOWED_USER_IDS') ?? process.env.ALLOWED_USER_IDS ?? ''
  let web = env.get('WEB_ENABLED') ?? process.env.WEB_ENABLED ?? 'true'
  let port = env.get('WEB_PORT') ?? DEFAULT_WEB_PORT

  if (!options.yes) {
    const rl = createInterface({ input: process.stdin, output: process.stdout })
    console.log('\n--- Configuration ---')
    token = (await ask(rl, `TELEGRAM_BOT_TOKEN [${token ? '***' : 'required'}]: `)).trim() || token
    ids = (await ask(rl, `ALLOWED_USER_IDS (comma-separated) [${ids || 'required'}]: `)).trim() || ids
    web = (await ask(rl, `Enable Web PWA? (true/false) [${web}]: `)).trim() || web
    port = (await ask(rl, `Web port (opencode itself uses 7081) [${port}]: `)).trim() || port
    rl.close()
  }

  if (!token) { console.error('TELEGRAM_BOT_TOKEN is required.'); process.exit(1) }
  if (!ids) { console.error('ALLOWED_USER_IDS is required.'); process.exit(1) }

  upsertEnv({
    TELEGRAM_BOT_TOKEN: token,
    ALLOWED_USER_IDS: ids,
    WEB_ENABLED: web,
    WEB_PORT: port,
  })
  console.log(`\n  Wrote config to ${ENV_FILE}`)

  writeBridge()
  console.log(`  Installed plugin bridge → ${BRIDGE_FILE}`)

  if (migrateLegacyConfig()) {
    console.log(`  Removed legacy directory-path plugin entry from ${GLOBAL_OPENCODE_JSON}`)
  }

  console.log(`\nInstallation complete!`)
  console.log(`\nNext steps:`)
  console.log(`   1. Point your Cloudflare tunnel ingress at http://localhost:${port}`)
  console.log(`   2. Run \`opencode\` from any directory — the plugin loads globally.`)
  console.log(`      Tip: for a always-on remote-control hub, run it from a small/empty`)
  console.log(`      dir (e.g. ~/ocrc-hub) so opencode's file watcher stays fast.`)
  console.log(`   3. Only run ONE opencode instance for remote control — web (:${port}) and`)
  console.log(`      the Telegram bot are global singletons.`)
}

export async function main(args: string[] = process.argv.slice(2)): Promise<void> {
  if (args.includes('--help') || args.includes('-h')) {
    console.log(`
opencode-remote-control install (opencode 1.17+)

USAGE:
  npm run build && node dist/cli/install.js [OPTIONS]

OPTIONS:
  --yes, -y   Skip interactive prompts (uses existing .env / env vars)
  --help, -h  Show this help

WHAT IT DOES:
  1. Writes a plugin bridge to ~/.config/opencode/plugins/ (1.17 loads local
     plugins from there; directory paths in opencode.json no longer work)
  2. Ensures ~/.config/opencode/package.json has "type": "module"
  3. Saves TELEGRAM_BOT_TOKEN / ALLOWED_USER_IDS / WEB_ENABLED / WEB_PORT to the
     repo's .env (1.17 plugins receive no options object, so config lives in .env)
  4. Removes any legacy directory-path plugin entry from opencode.json

NOTES:
  - Default web port is ${DEFAULT_WEB_PORT} (opencode's own server occupies 7081).
  - The bridge re-invokes the built dist, so rebuild dist + restart to update.
`)
    return
  }
  await runInstall({ yes: args.includes('--yes') || args.includes('-y') })
}

if (process.argv[1]?.endsWith('install.js') || process.argv[1]?.endsWith('install.ts')) {
  main().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
